### ISSUE TITLE
skipped batches

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#301]
I noticed that a small number of batches (30 in total) did not import. All, except possibly one, seem to be available in the SG database:

BatchID:
102841-102863
107348-107349
113161-113166

The import script I have is based on the notion that batches are created (and made available) in a sequential order, and all new import start from the highest batchID previously imported.

I am presuming that those batches were not available/visible at the time of the transfer to Motus, but I don't have a process currently to go back and re-import these batches. One work-around could be to build a list of gaps in the batchID sequence and try to import them individually. This word-around is manageable if the number of cases is small, and also assumes that those batchID will become available at some point in the future.

For that reason, it would therefore be preferable to continue to include all failed batches  (see issue #285) rather than removing them from the import process (though the numHits could be adjusted to zero or marked as failed in some other way).

An alternative approach would be to generate/re-issue the batchID number in the sequence in which batches become visible to the import queue, rather than based on when there were started, so that the import process is forward-only.

Any suggestions on how to deal with this?

**Comment by jbrzusto** [comment]
I'm not clear what you mean by "failed to import"?  Is it:

  **A)**  you received the batchID from one of the `batches_for_*` API calls but then did not receive the correct number of hits from the corresponding calls to `hits_for_*` API calls?  

or
  **B)**  you did a query from the mariadb command shell and found some batches with state < 1?

or something else?

The assumptions for your import script match the semantics of the master table merge and the data API, so should be fine.  

Case by case:
- the group with BatchIDs 102841-102863 are **testing** batches, and should not have been returned by the API unless you specified `"isTesting":true`, which isn't meant for pulling real data.
That group has `status=-1`  in the table at the end of this comment.  If you did *not* specify `"isTesting":true` but still received those batch IDs in a reply from one of the `batches_for_*` API calls, then there's a bug in `dataServer.R`  But if you just got those IDs by 

- the group with BatchIDs 107348-107349  had an error in the `pushToMotus()` because of some bug, yet to be determined.  But the record for the batches are in the table, and they both have `numHits=0`  so it appears as if the trasnfer to the master DB was correct.  Regardless, there were a number of jobs with errors in the replaying of all new uploads, and I'll be working through those to fix bugs etc.

- the group with BatchID 113161-113166  appear to be fully present in the master DB.  These batchIDs
should not have been returned until the batch had been marked with `state=1`, indicating all related records in other tables had already been inserted.   All of this happens in single-threaded code, so the transactions (inserts into the `runs` and `hits` tables for a given batch) are being launched in order, and completed before the update to the `batches` table.  However, it's possible the mysql server is performing some of these in parallel, which could lead to the `batches` record being marked ready `state=1` *before* the transactions to insert into `runs` and `hits` have completed.  

**So it's important to know** whether the data API returned these batchIDs but returned no hits
for them, or whether you ran a query to find batches with state < 1 and turn up the last set *while*
data were still being transferred to the master DB?  If so, then it doesn't seem there's a bug.
But if not, then I need to look further into the possibility of parallelism breaking the apparent
ordering of transactions, and then fix that.

--- 

State of the batches mentioned above:

```sql
MariaDB [motus]> select batchID, status from batches where     (batchID between 102841 and 102863) or (batchID between 107348 and 107349) or (batchID between 113161 and 113166);
+---------+--------+
| batchID | status |
+---------+--------+
|  102841 |     -1 |
|  102842 |     -1 |
|  102843 |     -1 |
|  102844 |     -1 |
|  102845 |     -1 |
|  102846 |     -1 |
|  102847 |     -1 |
|  102848 |     -1 |
|  102849 |     -1 |
|  102850 |     -1 |
|  102851 |     -1 |
|  102852 |     -1 |
|  102853 |     -1 |
|  102854 |     -1 |
|  102855 |     -1 |
|  102856 |     -1 |
|  102857 |     -1 |
|  102858 |     -1 |
|  102859 |     -1 |
|  102860 |     -1 |
|  102861 |     -1 |
|  102862 |     -1 |
|  102863 |     -1 |
|  107348 |    -10 |
|  107349 |    -10 |
|  113161 |      1 |
|  113162 |      1 |
|  113163 |      1 |
|  113164 |      1 |
|  113165 |      1 |
|  113166 |      1 |
+---------+--------+
```

**Comment by denislepage** [comment]
I incorrectly assumed that everything I saw under MariaDB was to be available through the API, and did not filter with status when querying directly the database. That resolves batches 102841-102863, with status = -1, and 107348-107349 with status = -10.

For the other sequence (113161-113166), I just confirmed these batchID’s are now being returned by the API (e.g., batches_for_all), but they were not initially when I did the import, suggesting that the status was changed from 0 to 1 after I did the import.  Just to confirm, I never used a status filter in my API calls, so should have only ever seen batches with status = 1, and in this case I am strictly taking about missing rows in batches, not any of the associated tables.

Because I always start from the last batchID read, I do not have a process to go back and read those batch records. IE, as soon as I read the batchID 113167 or higher, I don’t have a way to identify which older batches have been made available by a change of status. For argument sake, say I got up to 10,000 records starting at 113000 with batches_for_all. Because the status of 113161-113166 was initially 0, those were excluded from the results, and I got all batchID between 113000 and 114000 excluding those 6 batchID’s. Any subsequent calls that I make will be with a batchID greater than (or equal to) 114000, so even if the status of the 6 batches is changed after the fact, they will never be imported with the current process.

This is only a small number of consecutive batches, so clearly a rare occurrence, but unless I am not clearly understanding why those were initially missed, it still breaks the import logic. IE, no batches should be set to status = 1 until all previous batches (smaller batchID’s) have a status <> 0. The fact that this is rare may suggest that those batches were on a separate parallel thread that completed after some of the ones with a higher batchID, and also happened while I was running the import. If so, maybe setting a condition that batches can only be returned after a “cooling off period” could fix this. IE, to be visible to the API, a batch must have status = 1 and be completed since at least 10 minutes, or something safe that ensures that all parallel threads running at the same time also had time to complete.

**Comment by jbrzusto** [comment]
You're right - this shows that the logic for getting new batches based on batchID breaks down if
the data API requests come in while batches are being transferred, e.g. under this scenario:
- `processServer#1 (PS1)` allocates a block of `N` batchIDs in the master DB, starting at `M`
- `processServer#2 (PS2)` allocates a block of `P` batchIDs in the master DB, starting at `M + N`
- `PS1` starts inserting hits and runs for (large) batch `M`
- `PS2` starts inserting hits and runs for (small) batch `M + N`
- `PS2` finishes inserting hits and runs
- `PS2` inserts the batch record with `batchID = M + N`
- data client requests new batches with `batchID > M - 1`
- data server replies with `batchID = M + N`
- `PS1` finishes inserting hits and runs
- `PS1` inserts batch record with `batchID = M`
- data client requests new batches with `batchID > M + N`, so won't requests record for batch `M`

A similar error scenario will be possible as long as:
- batchIDs are obtained before corresponding complete records are written to the batches table
- more than one process can update the master database at a time

### Fix ###
I think the lowest-impact fix is to prevent concurrent update access to the master
database, so that complete records are added to the batches and related tables in order
of increasing batchID.

**Comment by jbrzusto** [comment]
Thorough exercising of this fix will probably only happen after syncing of networked receivers is
implemented on the new server.

**Comment by denislepage** [comment]
That's good for now. When the fix is in, we can go back and look for any other instances of this problem. I'm importing the 6 missing batches now.
