### ISSUE TITLE
missing batches, runs, gps and hits

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#316]
There are some batches no longer being returned by the API that are listed with status = 1 in MariaDB and should likely be returned. I tried with both using admin authentication and user authentication, with the same result.

batches_for_all and batches_for_receiver are both returning the batchID's, but none of the associated records (hits, runs or gps). 

batches_for_all with starting batchID = 113477, or batches_for_receiver (deviceID = 959, receiver = SG-0816BBBK0511) both return many batches between 113478 and 113524 that should have many hits, but nothing appears to be returned by runs_for_receivers, hits_for_receivers or gps_by_receiver.

tagme("SG-0816BBBK0511") illustrates the problem well.

Likewise, batches_for_project do not return some of the batch records, nor any of the associated records.

tagme(160) does not return batchID 113490, although this query returns records:

select * from runs where batchIDBegin = 113490 and tagDepProjectID = 160;

**Comment by jbrzusto** [comment]
- the batches in question have `recvDepProjectID = NULL`.  This field
  indicates which project owns the batch.

- the field is `NULL` because there is no deployment record for motus
device 959 aka `SG-0816BBBK0511` (or at least there was no such record
when the batch was created; updating this field after batch creation
is the subject of #267)

- all of the `*_for_receiver` APIs validate user authorization for the
  requested data by a join with the `batches` table that tests whether
  `batches.recvDepProjectID` is one of the user's projects.  If the
  test fails, the API returns with zero rows.

- the test is false if `recvDepProjectID = NULL`

So the behaviour you're seeing is (narrowly) correct, but obviously
admin users need a way to get all the linked runs, hits, gps, and
pulseCounts from such *unowned* batches.

A low-impact way to achieve this is for the server to ignore batch ownership
when the `*_for_receiver` caller is an administrator.

**Comment by jbrzusto** [comment]
SG-0816BBBK0511 is also subject to #317
