### ISSUE TITLE
missing motusUserID and motusProjectID in batches >= 114283

### ISSUE THREAD

**Issue by denislepage** [jbrzusto/motusServer#323]
All motusUserID and motusProjectID values are blank in batches where batchID >= 114283.

To confirm: motusProjectID in batches is the project that the user (motusUserID) has self-identify during the upload process?

**Comment by jbrzusto** [comment]
Yes.  However, if a receiver is fully re-run then the resulting new batches don't have 
`motusProjectID` or `motusUserID` set.

I'm not sure what makes the most sense here.  Rerunning a receiver, which occasionally
happens due to bugs in code, missed / disorganized data etc., is done by an admin user.

Neither of these fields is used in `dataServer()` for anything, although they are returned by
the `batches_for_*` API calls.  The project that 'owns' a batch (in terms of permissions to access the batch via the dataServer) is generated dynamically from receiver deployment metadata at the time the batch is entered into master table.

Perhaps this discussion needs to take place in [this context](https://github.com/jbrzusto/TO_DO/issues/138)

But a different angle on this issue is #331

**Comment by denislepage** [comment]
In theory, users won’t be accessing their data directly from SG data for anything. I believe that all queries will be sending to SG API will be using an admin accounts, including the new status API. So I’d be inclined to simply carry the values provided at the time of the file upload, and not attempt to make them consistent with the metadata. We are already handling the user permissions from here on that basis within the Motus API.

The motusUserID and motusProjectID are quite useful for us to have, and potentially address missing metadata, at least until we start accepting file uploads ourselves (at that point, we could ask and store that information here). If you are assigning null projectID because the metadata doesn’t exist, then we lose that utility.

**Comment by denislepage** [comment]
I will close this issue, assuming that the missing user and project ID's for past recent batches cannot be recovered. 

Reprocessed batches must be linkable to the original ones, which in turns should be linkable to individual upload events tied to a user and project. As we are transitioning the upload tools to Motus, we can ensure of the latter, but I still need to confirm that the upload event on Motus can be tied to individual batches that are coming out of the tag finder(?). In the event of a reprocesssing of a file and associated batches, the SG API should primarily need to ensure that it provides the original batchID in a new field for each of the newly re-generated batches, and we will handle the logic of the motusClient interactions within the motus API, along the lines of what is described [here](https://github.com/jbrzusto/motusServer/blob/new_server/inst/doc/motus_data_overview.md).
